### ISSUE TITLE
No donation means are suggested

### ISSUE THREAD

**Issue by LuccoJ** [caarmen/poet-assistant#13]
I am not a fan of programs nagging for donations, or even having such an option in their menu, and certainly not ones that use the Play Services to enabled that, so let me clarify that none of that is what I mean to suggest here.

Mainly, I'm thinking if you set up a Bitcoin address and published it on the Github README, it'd also propagate to F-Droid (which has a feature for direct Bitcoin donations as long as one has a Bitcoin wallet app installed), encouraging easy microdonations.

Maybe you don't care about getting money for this, but I think this is how open source software should mostly sustain itself, so just throwing it out there. Once a Bitcoin wallet is set up, maintaining it is virtually effortless, anyway.

**Comment by caarmen** [comment]
Hello Lucco,

Thank you very much for this suggestion.  At the moment, I'm not seeking any revenue from any of my hobby projects. 

I thought about maybe adding a link to donate to the FSF (https://my.fsf.org/donate/ ), with a text like "If you want to support free software, instead of donating to the developer of this app, consider making a donation to the Free Software Foundation".  But that might politicize my project :P  I'll think about it.

Cheers,
Carmen
