### ISSUE TITLE
bug found when try to use play btton

### ISSUE THREAD

**Issue by muhammadarif1** [caarmen/poet-assistant#140]
#### Expected behavior
This app should allow users to use the text to speech feature to read poems that have been written.
#### Actual behavior
but when I want to use the feature to read poems that I have written this app does not work as it should
#### How to reproduce
- download poet assistan from google play store
- launch the app
- scroll to the right side to the reader option
- write a few sentences and press play button. and see if the play button does not make any sound
* Browser: poet assistant 1.26.3
* Operating system: android 5.1 idos

#### Recording Of Thhe bug
 https://youtu.be/zrgmiMUs_VY

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@muhammadarif/bug-found-when-try-to-use-play-btton">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by caarmen** [comment]
Thanks for reporting this.
Could you go to the settings and see if the preview works?

**Comment by caarmen** [comment]
I can't reproduce this so far. The only time I thought I could reproduce it, it was because the text had some spaces at the end, and the cursor was just before these spaces. If the cursor is at the very end of the text, or at the very beginning of the text, the app reads the whole text. Otherwise, if the cursor is somewhere in the middle of the text, the app reads the text from that point to the end. So, if there's only spaces from that point to the end, you don't hear anything.

Is this your scenario? It's hard to see where the cursor is in the video.

The steps described in the issue description don't really match the video. In the video, there was already some text entered in, and the app was in the dictionary tab. Then you swiped to the reader tab to tap play.  You didn't tap play after writing a few sentences.  The exact steps could be important to being able to reproduce the issue.

**Comment by caarmen** [comment]
I've done a fix in 1.26.4, for the case where the cursor is positioned near the end of the text and only whitespace follows the cursor. Now, in this case, the whole text will be read.
