### ISSUE TITLE
Rhymer algorithm may be broken

### ISSUE THREAD

**Issue by LuccoJ** [caarmen/poet-assistant#5]
I see that the rhymer's database consists of the last three syllables for each word, but there is no information about which syllable is stressed. Two words rhyme if every phoneme starting from the stressed vowel until the end of the word is the same; with your system, instead, it seems that simple suffix matching is performed.

If I remember correctly, the CMU dictionary (at least some version of it) includes stress information, in the form of numbers indicating primary, secondary or tertiary stress (only primary stress should matter here).

I want to point out that there is another interesting possibility, though: http://espeak.sourceforge.net/ can generate a phonetic rendering in IPA for any word you give it if you call it as "espeak -q --ipa <word>", with the added bonus that it works for various languages and dialects (American and British English, for starters). You just need to feed it a wordlist, and then PoetAssistant could be expanded to support more languages.
Anyway, it could be a useful alternative even just for English. The stressed vowel is clearly marked with a ˈ sign so you can just match against everything that follows.

**Comment by caarmen** [comment]
Thanks for the info.  Indeed, stress isn't considered at this point, for the rhyming dictionary.  I stripped the numbers off of this list of symbols from the CMU dictionary, for this app: http://svn.code.sf.net/p/cmusphinx/code/trunk/cmudict/cmudict-0.7b.symbols  To be honest, it was because I didn't know the purpose of the numbers at the point :P  

In fact, I created the Reader part of the app to deal with stress, though in a less programmatic/exact way: I thought it helped to hear the text read out loud, to have an idea of whether the meter was as expected or not.

I'm curious how you discovered this project.  How did you find it? I just created this as a tool to help myself out on the rare occasions when I attempt to write a poem.  Previously it was annoying to jump between different websites for the various dictionaries, so I thought this might help.  But I didn't even expect any users :P

Please just note that this is a just a hobby app that I work on on my free time.  So I may not be able to address all your cool ideas right away :) But I appreciate the feedback!  The cross search rhymer/thesaurus (#3) and the search from the reader (#4) should be available soon.

**Comment by LuccoJ** [comment]
Stress may actually break fewer rhymes than I thought, in English. I was presently discussing this with some people from ##English on the freenode IRC network and none of us could come up with a convincing example of two words that don't rhyme because of stress, but otherwise end identically.
(But just think of "to insult" vs "the insult"... this is a silly example because they're spelled the same and are similar in meaning, but even though the phonemes are the exact same, the stress is not, and they don't rhyme.)

I found this app from F-Droid, which I use as my almost sole source for Android apps, and I always monitor it for new releases.

It's okay if you can't address all the issues I open - I can get down to coding (or at least try) if I really want them to happen. But it might be useful to have them described out there.

**Comment by caarmen** [comment]
It looks like it shouldn't be too difficult after all to take into account the stress, and look for rhymes based on the last stressed syllable to the end of the word. I'll see what kind of results that gives. I may end up adding a setting to the app to only include "strict" rhymes, versus "loose rhymes" and let the user choose. Might be useful in cases where the strict/technically proper rhyming rule doesn't yield enough results for some usages where loose rhyming might be ok (song writing I guess, and maybe some forms of poetry.)

**Comment by LuccoJ** [comment]
Yes, I agree it would be a good idea, and when we were discussing this stuff on IRC yesterday, we ended up making the almost identical reasoning that strict rhymes should be shown first, then loose rhymes separately, as they may be useful for song writing where there is no reader needing to guess the pronunciation.

In the future, you could perhaps even include assonance, by discounting the consonants and only looking at the vowel, for even looser rhyming. Personally I think that instead of a setting to decide what type to use, you could simply list strict rhyme first, then loose rhyme with a header making the distinction clear.
